services:
  backend:
    build:
      context: ../..
      dockerfile: src/infrastructure/backend/Dockerfile
    environment:
      - Jwt__Key=${JWT_SECRET}
    restart: unless-stopped

  caddy:
    build:
      context: ../..
      dockerfile: src/infrastructure/caddy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  caddy_data:
