services:
  backend-staging:
    container_name: backend-staging
    build:
      context: ../..
      dockerfile: src/infrastructure/backend/Dockerfile
    environment:
      - Jwt__Key=${JWT_SECRET}
    networks:
      - doko-net
    restart: unless-stopped

  frontend-staging:
    container_name: frontend-staging
    build:
      context: ../..
      dockerfile: src/infrastructure/caddy/Dockerfile.staging
    networks:
      - doko-net
    restart: unless-stopped

networks:
  doko-net:
    external: true
