// <auto-generated />
using System;
using Doko.Analog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Doko.Analog.Migrations
{
    [DbContext(typeof(AnalogDbContext))]
    [Migration("20260514232157_AddHeroCard")]
    partial class AddHeroCard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analog")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Doko.Analog.Entities.AnalogComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("comment", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogExtraPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("extra_point", "analog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Agathe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Doppelkopf"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fischauge"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fuchs gefangen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gans gefangen"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kaffeekränzchen"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Karlchen"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Klabautermann gefangen"
                        });
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogGameMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSolo")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SoloParty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("game_mode", "analog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSolo = false,
                            Name = "Armut"
                        },
                        new
                        {
                            Id = 2,
                            IsSolo = false,
                            Name = "Hochzeit"
                        },
                        new
                        {
                            Id = 3,
                            IsSolo = false,
                            Name = "Normal"
                        },
                        new
                        {
                            Id = 4,
                            IsSolo = true,
                            Name = "Bubensolo",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 5,
                            IsSolo = true,
                            Name = "Damensolo",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 6,
                            IsSolo = true,
                            Name = "Farbsolo",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 7,
                            IsSolo = true,
                            Name = "Fleischloses",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 8,
                            IsSolo = true,
                            Name = "Knochenloses",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 9,
                            IsSolo = true,
                            Name = "Kontrasolo",
                            SoloParty = 1
                        },
                        new
                        {
                            Id = 10,
                            IsSolo = true,
                            Name = "Schlanker Martin",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 11,
                            IsSolo = true,
                            Name = "Schwarze Sau",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 12,
                            IsSolo = true,
                            Name = "Stille Hochzeit",
                            SoloParty = 0
                        });
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HeroCard")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("StartingPoints")
                        .HasColumnType("decimal(10,1)");

                    b.HasKey("Id");

                    b.ToTable("player", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameModeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("WinningParty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameModeId");

                    b.ToTable("round", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRoundExtraPoint", b =>
                {
                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraPointId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("RoundId", "ExtraPointId", "TeamId");

                    b.HasIndex("ExtraPointId");

                    b.HasIndex("TeamId");

                    b.ToTable("round_extra_point", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRoundSpecialCard", b =>
                {
                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialCardId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("RoundId", "SpecialCardId", "TeamId");

                    b.HasIndex("SpecialCardId");

                    b.HasIndex("TeamId");

                    b.ToTable("round_special_card", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogSpecialCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("special_card", "analog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gegengenscherdamen"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Genscherdamen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Heidfrau"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Heidmann"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hyperschweinchen"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kemmerich"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Linksdrehender Gehängter"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Schweinchen"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Superschweinchen"
                        });
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Party")
                        .HasColumnType("integer");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("team", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogTeamMember", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("team_member", "analog");
                });

            modelBuilder.Entity("Doko.Analog.PlayerLeaderboardEntry", b =>
                {
                    b.Property<decimal>("AvgPointsPerGame")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_points_per_game");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<decimal>("TotalPoints")
                        .HasColumnType("numeric")
                        .HasColumnName("total_points");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("numeric")
                        .HasColumnName("win_rate");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.ToTable((string)null);

                    b.ToView("player_leaderboard", "analytics");
                });

            modelBuilder.Entity("Doko.Analog.PlayerRoundHistoryEntry", b =>
                {
                    b.Property<decimal>("CumulativePoints")
                        .HasColumnType("numeric")
                        .HasColumnName("cumulative_points");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<decimal>("PointDelta")
                        .HasColumnType("numeric")
                        .HasColumnName("point_delta");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer")
                        .HasColumnName("round_id");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean")
                        .HasColumnName("won");

                    b.ToTable((string)null);

                    b.ToView("player_round_history", "analytics");
                });

            modelBuilder.Entity("Doko.Analog.Stats.ExtraPointStatsEntry", b =>
                {
                    b.Property<decimal>("AvgGameValue")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_game_value");

                    b.Property<decimal>("AvgPointsWonLost")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_points_won_lost");

                    b.Property<int>("ExtraPointId")
                        .HasColumnType("integer")
                        .HasColumnName("extra_point_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("numeric")
                        .HasColumnName("win_rate");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.ToTable((string)null);

                    b.ToView("extra_point_stats", "analytics");
                });

            modelBuilder.Entity("Doko.Analog.Stats.GameModeStatsEntry", b =>
                {
                    b.Property<decimal>("AvgGameValue")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_game_value");

                    b.Property<int>("GameModeId")
                        .HasColumnType("integer")
                        .HasColumnName("game_mode_id");

                    b.Property<string>("GameModeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_mode_name");

                    b.Property<decimal?>("ReAvgGameValue")
                        .HasColumnType("numeric")
                        .HasColumnName("re_avg_game_value");

                    b.Property<decimal?>("ReWinRate")
                        .HasColumnType("numeric")
                        .HasColumnName("re_win_rate");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("integer")
                        .HasColumnName("total_rounds");

                    b.ToTable((string)null);

                    b.ToView("game_mode_stats", "analytics");
                });

            modelBuilder.Entity("Doko.Analog.Stats.PlayerExtraPointStatsEntry", b =>
                {
                    b.Property<decimal>("AvgGameValue")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_game_value");

                    b.Property<int>("ExtraPointId")
                        .HasColumnType("integer")
                        .HasColumnName("extra_point_id");

                    b.Property<string>("ExtraPointName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extra_point_name");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("numeric")
                        .HasColumnName("win_rate");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.ToTable((string)null);

                    b.ToView("player_extra_point_stats", "analytics");
                });

            modelBuilder.Entity("Doko.Analog.Stats.PlayerGameModeStatsEntry", b =>
                {
                    b.Property<decimal>("AvgGameValue")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_game_value");

                    b.Property<decimal>("AvgPointsEarned")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_points_earned");

                    b.Property<decimal>("AvgPointsWonLost")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_points_won_lost");

                    b.Property<int>("GameModeId")
                        .HasColumnType("integer")
                        .HasColumnName("game_mode_id");

                    b.Property<string>("GameModeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_mode_name");

                    b.Property<int>("Games")
                        .HasColumnType("integer")
                        .HasColumnName("games");

                    b.Property<int>("Party")
                        .HasColumnType("integer")
                        .HasColumnName("party");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("numeric")
                        .HasColumnName("win_rate");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.ToTable((string)null);

                    b.ToView("player_game_mode_stats", "analytics");
                });

            modelBuilder.Entity("Doko.Analog.Stats.PlayerPartnerStatsEntry", b =>
                {
                    b.Property<decimal>("AvgPointsWonLost")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_points_won_lost");

                    b.Property<int>("GamesTogether")
                        .HasColumnType("integer")
                        .HasColumnName("games_together");

                    b.Property<int>("PartnerId")
                        .HasColumnType("integer")
                        .HasColumnName("partner_id");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partner_name");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<decimal>("WinRateTogether")
                        .HasColumnType("numeric")
                        .HasColumnName("win_rate_together");

                    b.Property<int>("WinsTogether")
                        .HasColumnType("integer")
                        .HasColumnName("wins_together");

                    b.ToTable((string)null);

                    b.ToView("player_partner_stats", "analytics");
                });

            modelBuilder.Entity("Doko.Analog.Stats.PlayerSpecialCardStatsEntry", b =>
                {
                    b.Property<decimal>("AvgGameValue")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_game_value");

                    b.Property<decimal>("AvgPointsWonLost")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_points_won_lost");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("SpecialCardId")
                        .HasColumnType("integer")
                        .HasColumnName("special_card_id");

                    b.Property<string>("SpecialCardName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("special_card_name");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("numeric")
                        .HasColumnName("win_rate");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.ToTable((string)null);

                    b.ToView("player_special_card_stats", "analytics");
                });

            modelBuilder.Entity("Doko.Analog.Stats.PlayerStatsEntry", b =>
                {
                    b.Property<decimal>("AloneAvgPointsEarned")
                        .HasColumnType("numeric")
                        .HasColumnName("alone_avg_points_earned");

                    b.Property<int>("AloneGames")
                        .HasColumnType("integer")
                        .HasColumnName("alone_games");

                    b.Property<decimal>("AloneWinRate")
                        .HasColumnType("numeric")
                        .HasColumnName("alone_win_rate");

                    b.Property<int>("AloneWins")
                        .HasColumnType("integer")
                        .HasColumnName("alone_wins");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<decimal>("SoloAvgGameValue")
                        .HasColumnType("numeric")
                        .HasColumnName("solo_avg_game_value");

                    b.Property<decimal>("SoloAvgPointsWonLost")
                        .HasColumnType("numeric")
                        .HasColumnName("solo_avg_points_won_lost");

                    b.Property<int>("SoloGames")
                        .HasColumnType("integer")
                        .HasColumnName("solo_games");

                    b.Property<decimal>("SoloWinRate")
                        .HasColumnType("numeric")
                        .HasColumnName("solo_win_rate");

                    b.Property<int>("SoloWins")
                        .HasColumnType("integer")
                        .HasColumnName("solo_wins");

                    b.Property<decimal>("TotalAvgGameValue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_avg_game_value");

                    b.Property<decimal>("TotalAvgPointsEarned")
                        .HasColumnType("numeric")
                        .HasColumnName("total_avg_points_earned");

                    b.Property<decimal>("TotalAvgPointsWonLost")
                        .HasColumnType("numeric")
                        .HasColumnName("total_avg_points_won_lost");

                    b.Property<int>("TotalGames")
                        .HasColumnType("integer")
                        .HasColumnName("total_games");

                    b.Property<decimal>("TotalWinRate")
                        .HasColumnType("numeric")
                        .HasColumnName("total_win_rate");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer")
                        .HasColumnName("total_wins");

                    b.ToTable((string)null);

                    b.ToView("player_stats", "analytics");
                });

            modelBuilder.Entity("Doko.Analog.Stats.SpecialCardStatsEntry", b =>
                {
                    b.Property<decimal>("AvgGameValue")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_game_value");

                    b.Property<decimal>("AvgPointsWonLost")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_points_won_lost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences");

                    b.Property<int>("SpecialCardId")
                        .HasColumnType("integer")
                        .HasColumnName("special_card_id");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("numeric")
                        .HasColumnName("win_rate");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.ToTable((string)null);

                    b.ToView("special_card_stats", "analytics");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogComment", b =>
                {
                    b.HasOne("Doko.Analog.Entities.AnalogRound", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRound", b =>
                {
                    b.HasOne("Doko.Analog.Entities.AnalogGameMode", "GameMode")
                        .WithMany()
                        .HasForeignKey("GameModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameMode");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRoundExtraPoint", b =>
                {
                    b.HasOne("Doko.Analog.Entities.AnalogExtraPoint", "ExtraPoint")
                        .WithMany()
                        .HasForeignKey("ExtraPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doko.Analog.Entities.AnalogRound", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doko.Analog.Entities.AnalogTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraPoint");

                    b.Navigation("Round");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRoundSpecialCard", b =>
                {
                    b.HasOne("Doko.Analog.Entities.AnalogRound", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doko.Analog.Entities.AnalogSpecialCard", "SpecialCard")
                        .WithMany()
                        .HasForeignKey("SpecialCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doko.Analog.Entities.AnalogTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");

                    b.Navigation("SpecialCard");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogTeam", b =>
                {
                    b.HasOne("Doko.Analog.Entities.AnalogRound", "Round")
                        .WithMany("Teams")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogTeamMember", b =>
                {
                    b.HasOne("Doko.Analog.Entities.AnalogPlayer", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doko.Analog.Entities.AnalogTeam", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRound", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogTeam", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
