// <auto-generated />
using System;
using Doko.Analog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Doko.Analog.Migrations
{
    [DbContext(typeof(AnalogDbContext))]
    partial class AnalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analog")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Doko.Analog.Entities.AnalogComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("comment", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogExtraPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("extra_point", "analog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Agathe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Doppelkopf"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fischauge"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fuchs gefangen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gans gefangen"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kaffeekränzchen"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Karlchen"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Klabautermann gefangen"
                        });
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogGameMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSolo")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SoloParty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("game_mode", "analog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSolo = false,
                            Name = "Armut"
                        },
                        new
                        {
                            Id = 2,
                            IsSolo = false,
                            Name = "Hochzeit"
                        },
                        new
                        {
                            Id = 3,
                            IsSolo = false,
                            Name = "Normal"
                        },
                        new
                        {
                            Id = 4,
                            IsSolo = true,
                            Name = "Bubensolo",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 5,
                            IsSolo = true,
                            Name = "Damensolo",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 6,
                            IsSolo = true,
                            Name = "Farbsolo",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 7,
                            IsSolo = true,
                            Name = "Fleischloses",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 8,
                            IsSolo = true,
                            Name = "Knochenloses",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 9,
                            IsSolo = true,
                            Name = "Kontrasolo",
                            SoloParty = 1
                        },
                        new
                        {
                            Id = 10,
                            IsSolo = true,
                            Name = "Schlanker Martin",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 11,
                            IsSolo = true,
                            Name = "Schwarze Sau",
                            SoloParty = 0
                        },
                        new
                        {
                            Id = 12,
                            IsSolo = true,
                            Name = "Stille Hochzeit",
                            SoloParty = 0
                        });
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("StartingPoints")
                        .HasColumnType("decimal(10,1)");

                    b.HasKey("Id");

                    b.ToTable("player", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameModeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("WinningParty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameModeId");

                    b.ToTable("round", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRoundExtraPoint", b =>
                {
                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraPointId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("RoundId", "ExtraPointId", "TeamId");

                    b.HasIndex("ExtraPointId");

                    b.HasIndex("TeamId");

                    b.ToTable("round_extra_point", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRoundSpecialCard", b =>
                {
                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialCardId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("RoundId", "SpecialCardId", "TeamId");

                    b.HasIndex("SpecialCardId");

                    b.HasIndex("TeamId");

                    b.ToTable("round_special_card", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogSpecialCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("special_card", "analog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gegengenscherdamen"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Genscherdamen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Heidfrau"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Heidmann"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hyperschweinchen"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kemmerich"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Linksdrehender Gehängter"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Schweinchen"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Superschweinchen"
                        });
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Party")
                        .HasColumnType("integer");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("team", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogTeamMember", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("team_member", "analog");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogComment", b =>
                {
                    b.HasOne("Doko.Analog.Entities.AnalogRound", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRound", b =>
                {
                    b.HasOne("Doko.Analog.Entities.AnalogGameMode", "GameMode")
                        .WithMany()
                        .HasForeignKey("GameModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameMode");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRoundExtraPoint", b =>
                {
                    b.HasOne("Doko.Analog.Entities.AnalogExtraPoint", "ExtraPoint")
                        .WithMany()
                        .HasForeignKey("ExtraPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doko.Analog.Entities.AnalogRound", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doko.Analog.Entities.AnalogTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraPoint");

                    b.Navigation("Round");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogRoundSpecialCard", b =>
                {
                    b.HasOne("Doko.Analog.Entities.AnalogRound", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doko.Analog.Entities.AnalogSpecialCard", "SpecialCard")
                        .WithMany()
                        .HasForeignKey("SpecialCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doko.Analog.Entities.AnalogTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");

                    b.Navigation("SpecialCard");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogTeam", b =>
                {
                    b.HasOne("Doko.Analog.Entities.AnalogRound", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Doko.Analog.Entities.AnalogTeamMember", b =>
                {
                    b.HasOne("Doko.Analog.Entities.AnalogPlayer", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doko.Analog.Entities.AnalogTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
